### ISSUE TITLE
Jazzband

### ISSUE THREAD

**Issue by ticosax** [aldjemy/aldjemy#106]
Dear maintainers, have you considered moving this project under the jazzband organization ?

https://jazzband.co/

I could, then, cut a release and maintain the project for tasks I feel comfortable with, like make it work along new django releases as they are published.

**Comment by ryanhiebert** [comment]
I have not, but could be willing to. I'm a part of Jazzband myself, though I am not active.

I know that it would require me to automate deployments, which is my intent here as well. Past that, the benefit would be access to more maintainers. I try to be open here. Are you willing to assist in maintenance on this project?

**Comment by ticosax** [comment]
yes, I'm open for anything that would help you make new releases.
The advantage of jazzband, is that this organization provides code snippet and processes to simplify the maintenance. But keeping the project under aldjemy umbrella is also fine.

**Comment by ryanhiebert** [comment]
I see that you're already a part of the organization, sorry, I missed who I was talking to, for some reason I thought it was from the other issue asking for a release.

**Comment by ryanhiebert** [comment]
It is my understanding that one of Jazzband's requirements is that it be given a maintainer role on the PyPI project. I am not able to do that, because I only have a maintainer role myself. @Deepwalker , would you be willing to give me an owner role on the PyPI package?

Thanks, @ticosax , for the work you're putting in to getting this repo working nicely. I appreciate it very much!

**Comment by Deepwalker** [comment]
Sure. Own it :)

**Comment by ryanhiebert** [comment]
Thank you!
