### ISSUE TITLE
SAWarning on EmailAddress

### ISSUE THREAD

**Issue by Mogost** [aldjemy/aldjemy#205]
```
/lib/python3.8/site-packages/aldjemy/orm.py:160: 
SAWarning: This declarative base already contains a class with the same class name and module name 
as aldjemy.orm.EmailAddress, and will be replaced in the string-lookup table.
mapper_registry.map_imperatively(sa_model, local_table=table, properties=attrs)
```
Probably after https://github.com/aldjemy/aldjemy/commit/150353d53b5837b9a02c884c98b0f4df1fc88f9f

django 3.2
aldjemy 2.3

**Comment by ryanhiebert** [comment]
@ticosax any thoughts? @Mogost are you able to give a minimal reproduction?

**Comment by ticosax** [comment]
Thanks @Mogost, we haven't experienced this regression with our own project. 
We would need more information to reproduce and hopefully get a fix for it.

**Comment by Mogost** [comment]
@ticosax Apparently this is due to the fact that in my project there is a model class named `EmailAddress`
I quickly tried renaming and the error went away.  But even so, from the point of view of django, name is correct. And I'm not sure that rename is the right decision.

```
class EmailAddress(models.Model):
    created = models.DateTimeField(default=timezone.now, verbose_name=_('Created'))
    user = models.ForeignKey(Employee, models.CASCADE, related_name='email_addresses', verbose_name=_('User'))
    domain = models.CharField(max_length=254, verbose_name=_('Domain'))
    email = models.EmailField(unique=True, verbose_name=_('Email'))
    primary = models.BooleanField(default=False, verbose_name=_('Primary'))
```

**Comment by ticosax** [comment]
I'm sorry, that's not enough information for me.
Did you try to write a reproducible test case ?

**Comment by ryanhiebert** [comment]
> Assuming your postgres database's schema is `public`.

I don't think Aldjemy introspects the database, so I expect you should be able to produce the same result even if you use the incorrect schema name.

**Comment by tim-schilling** [comment]
Yeah, I was able to confirm this. If you have models with the same name in two different apps, calling `construct_models` will cause this warning to be raised when [`mapper_registry.map_imperatively(sa_model, local_table=table, properties=attrs)`](https://github.com/aldjemy/aldjemy/blob/main/aldjemy/orm.py#L165) is executed where the second `sa_model` is used. This is likely due to using `model._meta.object_name` for the dynamic class name [here](https://github.com/aldjemy/aldjemy/blob/main/aldjemy/orm.py#L148).

This is probably a bit difficult to resolve since it's a core difference between the Django ORM and SQLAlchemy. The core question is how do you generate the SQLAlchemy models for the following models?

```
auth.Group
myapp.Group
```
One option would be to return the sqlalchemy models with the table names rather than the Django object names. That way you know they'd be unique. Another would be to return them as their app model name: `f"{app.name}_{model._meta.object_name}"`. Both are unintuitive from the Django side.

**Comment by tim-schilling** [comment]
Nope, but if you add a model named `Group` to your [test_project](https://github.com/aldjemy/aldjemy/blob/main/test_project/sample/models.py) in the repo, it should reproduce the issue.

**Comment by tim-schilling** [comment]
Thanks for the quick change @ryanhiebert!

**Comment by ryanhiebert** [comment]
You bet! Thanks, @tim-schilling , for making it easy to reproduce and giving me some really good hints!
